Add missing word on comparison.md (add an "and")
vendorsec/mvsp pull request #83
Opened 2024-04-30 21:50 UTC by infosecdr

First sentence was missing an "and".

(maybe also the following "the" should be removed)

2024-04-30 22:33 UTC, acskurucz requested changes
Thanks! Reading it again "... and commonly used" does indeed sound better without the additional the. Would you mind removing that too please?

2024-05-03 17:00 UTC, infosecdr commented
Sure thing, done!

2024-05-03 17:01 UTC, acskurucz approved these changes

2024-05-03 17:01 UTC, acskurucz commented
Thank you!

2024-05-03 17:01 UTC, merged